# Generated by Django 4.2.1 on 2024-04-17 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("md_name", models.CharField(default="", max_length=100)),
                ("md_info", models.CharField(default="", max_length=250)),
                ("md_image", models.ImageField(default="", upload_to="models/")),
                ("md_file", models.FileField(default="", upload_to="models_files/")),
                ("md_owner_name", models.CharField(default="", max_length=50)),
                (
                    "md_rating",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(5)],
                    ),
                ),
                ("md_upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
