# Generated by Django 4.2.1 on 2024-04-16 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_name", models.CharField(default="", max_length=100)),
                ("db_info", models.CharField(default="", max_length=250)),
                ("db_image", models.ImageField(default="", upload_to="datasets/")),
                ("db_owner_name", models.CharField(default="", max_length=50)),
                (
                    "db_rating",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(5)],
                    ),
                ),
                ("db_upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
