# Generated by Django 4.2.1 on 2024-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="db_file",
            field=models.FileField(default="", upload_to="datasets_files/"),
        ),
    ]
