# Generated by Django 4.2.1 on 2024-05-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0003_database_db_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="db_price",
            field=models.IntegerField(default=0),
        ),
    ]
